apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploying
  namespace: nikithaspace
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: docker
        image: acrcontainer28.azurecr.io/acrcontainer28:1.0.0
        ports:
         - containerPort: 80
      imagePullSecrets:
       - name: acr-secret1
