apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploying
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: docker
        image: nikitha2109/docker-11-app:1.0.1
        ports:
         - containerPort: 80
