apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploying
  labels:
    app: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
      - name: docker
        image: docker-11-app:latest

        ports:
        - containerPort: 80
