apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploying
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nbyreddy/dockerdep-10-app:1.0.0
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
        env:
        - name: config_key1
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: config_key1
        - name: secret_key
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: secret_key
      
