apiVersion : apps/v1
kind: Deployment
metadata:
  name: devopsimage 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsimage
  template:
    metadata:
      labels:
        app: devopsimage 
    spec:
      containers:
        - name: devopsimage 
          image: clusters.azurecr.io/devopsimage
          ports:
          - containerPort: 5000